In [36]:
import yfinance as yf

In [37]:
hoon = yf.Ticker('ptt.bk')

In [40]:
interval = '1d'
start = '2023-9-12'
end = '2023-9-16'

hoon_price_df = hoon.history(interval='1h',start=start,end=end)
hoon_price_df

,Open,High,Low,Close,Volume,Dividends,Stock Splits
Datetime,,,,,,,
2023-09-12 10:00:00+07:00,34.75,34.75,34.50,34.75,0,0.0,0.0
2023-09-12 11:00:00+07:00,34.50,34.75,34.50,34.50,1801173,0.0,0.0
2023-09-12 12:00:00+07:00,34.50,34.75,34.25,34.50,11223786,0.0,0.0
2023-09-12 14:00:00+07:00,34.50,34.75,34.25,34.75,21894594,0.0,0.0
2023-09-12 15:00:00+07:00,34.75,34.75,34.25,34.50,4758347,0.0,0.0
2023-09-12 16:00:00+07:00,34.25,34.50,34.25,34.50,979126,0.0,0.0
2023-09-13 10:00:00+07:00,34.50,34.50,34.00,34.25,22919117,0.0,0.0
2023-09-13 11:00:00+07:00,34.25,34.50,34.25,34.25,11884416,0.0,0.0
2023-09-13 12:00:00+07:00,34.50,34.50,34.25,34.50,954912,0.0,0.0
2023-09-13 14:00:00+07:00,34.25,34.50,34.25,34.25,959115,0.0,0.0
2023-09-13 15:00:00+07:00,34.25,35.00,34.25,34.75,23204616,0.0,0.0
2023-09-13 16:00:00+07:00,34.75,35.00,34.50,34.75,12649014,0.0,0.0
2023-09-14 10:00:00+07:00,34.75,35.00,34.50,34.50,0,0.0,0.0
2023-09-14 11:00:00+07:00,34.75,34.75,34.50,34.75,1113565,0.0,0.0
2023-09-14 12:00:00+07:00,34.50,34.75,34.50,34.75,723084,0.0,0.0
2023-09-14 14:00:00+07:00,34.50,34.75,34.50,34.50,1122851,0.0,0.0
2023-09-14 15:00:00+07:00,34.50,34.75,34.50,34.75,2220884,0.0,0.0
2023-09-14 16:00:00+07:00,34.50,34.75,34.50,34.75,1981892,0.0,0.0
2023-09-15 10:00:00+07:00,34.75,35.00,34.50,35.00,0,0.0,0.0
2023-09-15 11:00:00+07:00,35.00,35.00,34.75,35.00,674265,0.0,0.0
2023-09-15 12:00:00+07:00,34.75,35.00,34.75,35.00,398917,0.0,0.0
2023-09-15 14:00:00+07:00,35.00,35.00,34.75,35.00,1284634,0.0,0.0
2023-09-15 15:00:00+07:00,34.75,35.00,34.75,35.00,3210823,0.0,0.0
2023-09-15 16:00:00+07:00,35.00,35.25,34.75,35.00,8706520,0.0,0.0

In [41]:
hoon.financials

,2022-12-31,2021-12-31,2020-12-31,2019-12-31
Tax Effect Of Unusual Items,-26692579452.799999,-8768979171.982939,4778900741.711571,3196346789.042191
Tax Rate For Calcs,0.4,0.307708,0.386486,0.212721
Normalized EBITDA,481639076010.0,422141699373.0,220523884236.0,299616361867.0
Total Unusual Items,-66731448632.0,-28497734654.0,12365016884.0,15026001823.0
Total Unusual Items Excluding Goodwill,-66731448632.0,-28497734654.0,12365016884.0,15026001823.0
Net Income From Continuing Operation Net Minority Interest,91174857528.0,108363410834.0,37765808355.0,92950604143.0
Reconciled Depreciation,167329599023.0,146789779649.0,139879640255.0,133204181804.0
Reconciled Cost Of Revenue,2906725865808.0,1882251511450.0,1446649069758.0,1967529006367.0
EBITDA,414907627378.0,393643964719.0,232888901120.0,314642363690.0
EBIT,247578028355.0,246854185070.0,93009260865.0,181438181886.0
Net Interest Income,-33170000000.0,-25641000000.0,-24603000000.0,-20134490000.0
Interest Expense,35016000000.0,27196000000.0,27893000000.0,26357700000.0
Interest Income,3921000000.0,2522000000.0,3933000000.0,7836970000.0
Normalized Income,131213726707.199997,128092166316.017059,30179692212.711571,81120949109.042191
Net Income From Continuing And Discontinued Operation,91174857528.0,108363410834.0,37765808355.0,92950604143.0
Total Expenses,3078457512984.0,2010520426133.0,1556038170833.0,2077987499586.0
Rent Expense Supplemental,2175000000.0,NaN,NaN,10359620000.0
Total Operating Income As Reported,243803904609.0,238811351503.0,89475010480.0,177043956036.0
Diluted Average Shares,28562996250.0,28562996250.0,28562996250.0,28562996250.0
Basic Average Shares,28562996250.0,28562996250.0,28562996250.0,28562996250.0
Diluted EPS,3.2,3.79,1.32,3.2
Basic EPS,3.2,3.79,1.32,3.2
Diluted NI Availto Com Stockholders,91391101037.0,108137909412.0,37611239926.0,91458925939.0
Net Income Common Stockholders,91391101037.0,108137909412.0,37611239926.0,91458925939.0
Otherunder Preferred Stock Dividend,-216243509.0,225501422.0,154568429.0,1491678204.0
Net Income,91174857528.0,108363410834.0,37765808355.0,92950604143.0
Minority Interests,-30924808524.0,-43704207013.0,-2183956559.0,-29140995793.0
Net Income Including Noncontrolling Interests,122099666052.0,152067617847.0,39949764914.0,122091599936.0
Net Income Discontinuous Operations,NaN,NaN,NaN,0.0
Net Income Continuous Operations,122099666052.0,152067617847.0,39949764914.0,122091599936.0
Tax Provision,90462362303.0,67590567223.0,25166495951.0,32988881950.0
Pretax Income,212562028355.0,219658185070.0,65116260865.0,155080481886.0
Other Income Expense,-43013464047.0,-2998612066.0,30092740077.0,33463801390.0
Other Non Operating Income Expenses,17869000000.0,16489000000.0,13550000000.0,12429810000.0
Special Income Charges,1886000000.0,9419000000.0,365000000.0,NaN
Gain On Sale Of Ppe,1886000000.0,-1275000000.0,-316000000.0,NaN
Other Special Charges,NaN,NaN,-681000000.0,NaN
Restructuring And Mergern Acquisition,0.0,-10694000000.0,NaN,NaN
Earnings From Equity Interest,5848984585.0,9010122588.0,4177723193.0,6007989567.0
Gain On Sale Of Security,-68617448632.0,-37916734654.0,12000016884.0,15026001823.0
Net Non Operating Interest Income Expense,-33170000000.0,-25641000000.0,-24603000000.0,-20134490000.0
Total Other Finance Cost,2075000000.0,967000000.0,643000000.0,1613760000.0
Interest Expense Non Operating,35016000000.0,27196000000.0,27893000000.0,26357700000.0
Interest Income Non Operating,3921000000.0,2522000000.0,3933000000.0,7836970000.0
Operating Income,288745487016.0,248297573867.0,59626829167.0,141751170414.0
Operating Expense,171731647176.0,128268914683.0,109389101075.0,110458493219.0
Other Operating Expenses,27504417516.0,17978441667.0,13398302136.0,17882466882.0
Selling General And Administration,144227229660.0,110290473016.0,95990798939.0,92576026337.0
Selling And Marketing Expense,46212116583.0,27245591322.0,27199413803.0,27573729167.0
General And Administrative Expense,98015113077.0,83044881694.0,68791385136.0,65002297170.0
Other Gand A,98015113077.0,83044881694.0,68791385136.0,65002297170.0
Gross Profit,460477134192.0,376566488550.0,169015930242.0,252209663633.0
Cost Of Revenue,2906725865808.0,1882251511450.0,1446649069758.0,1967529006367.0
Total Revenue,3367203000000.0,2258818000000.0,1615665000000.0,2219738670000.0
Operating Revenue,3366649000000.0,2258446000000.0,1614687000000.0,2218317470000.0

In [42]:
hoon.balancesheet

,2022-12-31,2021-12-31,2020-12-31,2019-12-31
Ordinary Shares Number,28562996250.0,28562996250.0,28562996250.0,28562996250.0
Share Issued,28562996250.0,28562996250.0,28562996250.0,28562996250.0
Net Debt,749667483264.0,572885069699.0,410700863582.0,357931453236.0
Total Debt,1193593039581.0,949824888442.0,795502787591.0,658968663236.0
Tangible Book Value,726576040828.0,679178458545.0,706573249068.0,686703302898.0
...,...,...,...,...
Cash Cash Equivalents And Short Term Investments,354578205272.0,363671031239.0,418137108278.0,330230580000.0
Other Short Term Investments,14524205272.0,50941031239.0,86105108278.0,38263310000.0
Cash And Cash Equivalents,340054000000.0,312730000000.0,332032000000.0,291967270000.0
Cash Equivalents,339918000000.0,312203000000.0,331646000000.0,291411400000.0
Cash Financial,136000000.0,527000000.0,386000000.0,555870000.0

In [43]:
hoon.cashflow

,2022-12-31,2021-12-31,2020-12-31,2019-12-31
Free Cash Flow,18454283626.0,179799875610.0,68252759502.0,114209424173.0
Repurchase Of Capital Stock,NaN,NaN,0.0,-1187603325.0
Repayment Of Debt,-201115333278.0,-113536169936.0,-82363943435.0,-134328404916.0
Issuance Of Debt,289780174199.0,207295898664.0,210692854323.0,194559624488.0
Issuance Of Capital Stock,9033732110.0,55153961522.0,267651233.0,18346174140.0
...,...,...,...,...
Earnings Losses From Equity Investments,-5848984585.0,-9010122588.0,-4177723193.0,-6007989567.0
Gain Loss On Investment Securities,16617676764.0,-791178953.0,3977509405.0,2961852356.0
Net Foreign Currency Exchange Gain Loss,11648818620.0,18977894183.0,-3682982828.0,-8259060713.0
Gain Loss On Sale Of Business,NaN,NaN,NaN,0.0
Net Income From Continuing Operations,212562028355.0,219658185070.0,65116260865.0,92950604143.0

In [44]:
all_ticker_list = ['STA.bk', 'TRUE.bk', 'SCB.bk']

In [45]:
all_financials = []
for ticker in all_ticker_list:
    financials_dict = dict()
    financials_dict[ticker] = yf.Ticker(ticker).financials
    all_financials.append(financials_dict)

In [46]:
all_selected = []
for fi in all_financials:
    fi_key = list(fi.keys())[0]
    fi_value = list(fi.values())[0]
    try:
        if fi_value.iloc[:,0]['Net Income'] > 0:
            all_selected.append(fi_key)
    except:
        pass

In [47]:
print(len(all_financials))
print(len(all_selected))

3
1

In [48]:
all_selected

['STA.bk']